### ISSUE TITLE
Avatars cannot be displayed

### ISSUE THREAD

**Issue by saillin** [alexandrevicenzi/soho#3]
config.toml configuration `profilePicture = "images/profile.png"`
I added profile.png in `/usr/local/lib/blog/themes/soho/images`
Local preview cannot display avatar

**Comment by alexandrevicenzi** [comment]
You should place in `.../soho/static/images/profile.png`.

**Comment by saillin** [comment]
> 您应该放置在中`.../soho/static/images/profile.png`。
Ok i should create an avatar at gravatar.com
