### ISSUE TITLE
Host on GitLab

### ISSUE THREAD

**Issue by saillin** [alexandrevicenzi/soho#4]
That’s it! You can now follow the CI agent building your page at https://gitlab.com/<YourUsername>/<your-hugo-site>/pipelines.
An error occurred：
` Running with gitlab-runner 13.1.0-rc1 (b9d289ed)
   on docker-auto-scale fa6cab46
Preparing the "docker+machine" executor
00:15
 Using Docker executor with image monachus/hugo ...
 Pulling docker image monachus/hugo ...
 Using docker image sha256:c016030df1af27eb35a1a98639e523abfa8a55d83ac7170c4062b1c01ff10fb6 for monachus/hugo ...
Preparing environment
00:04
 Running on runner-fa6cab46-project-19506480-concurrent-0 via runner-fa6cab46-srm-1592808650-50dbcc5e...
Getting source from Git repository
00:07
 $ eval "$CI_PRE_CLONE_SCRIPT"
 Fetching changes with git depth set to 50...
 Initialized empty Git repository in /builds/saillin199/saillin199.gitlab.io/.git/
 Created fresh repository.
 Checking out 19ab32f6 as master...
 Updating/initializing submodules recursively...
 fatal: No url found for submodule path 'themes/soho' in .gitmodules
 ERROR: Job failed: exit code 1`
Thank you

**Comment by saillin** [comment]
My vim .gitmodules
`[submodule "themes/soho"]
	path = themes/soho
	url = https://github.com/alexandrevicenzi/soho.git`
Run successfully
Thank you

**Comment by alexandrevicenzi** [comment]
This is not an error in the theme, it's your configuration. I'm not really here to help you debug your environment.

The way you should do on your side is probably something like this:

On your repo, add this project as a submodule and push it to your repo:

git submodule add <this project>

On any CI or build service do this after cloning the repo and before building:

git submodule update --recursive

This may not fix everything, but at least is a start for you.

**Comment by saillin** [comment]
> 这不是主题错误，是您的配置。我并不是真的在这里帮助您调试环境。
> 
> 您应该站在一边的方式可能是这样的：
> 
> 在您的仓库中，将该项目添加为子模块并将其推送到您的仓库中：
> 
> git子模块添加
> 
> 在克隆回购之后且在构建之前，请在任何配置项或构建服务上执行以下操作：
> 
> git子模块更新-递归
> 
> 这可能无法解决所有问题，但至少对您而言是一个开始。

I have solved it, thanks for your reply

**Comment by saillin** [comment]
> This is not an error in the theme, it's your configuration. I'm not really here to help you debug your environment.
> 
> The way you should do on your side is probably something like this:
> 
> On your repo, add this project as a submodule and push it to your repo:
> 
> git submodule add
> 
> On any CI or build service do this after cloning the repo and before building:
> 
> git submodule update --recursive
> 
> This may not fix everything, but at least is a start for you.
I have solved it, thanks for your reply

**Comment by saillin** [comment]
I have solved it, thanks for your reply
